# Generated by Django 2.0 on 2017-12-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=20)),
                ('damage', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('consumable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP', models.IntegerField()),
                ('HD', models.IntegerField(default=6)),
                ('INT', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='character.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Stats'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
