# Generated by Django 2.0 on 2017-12-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_cha_con_dex_hd_hp_int_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='stats',
        ),
        migrations.AlterField(
            model_name='cha',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='con',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dex',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hd',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hp',
            name='HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='int',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='str',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
