# Generated by Django 2.0 on 2017-12-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20171203_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con',
            name='val',
            field=models.IntegerField(),
        ),
    ]
