# Generated by Django 2.0 on 2017-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20171203_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
