# Generated by Django 2.0 on 2017-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20171203_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
