# Generated by Django 2.0 on 2017-12-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_race'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHA',
        ),
        migrations.DeleteModel(
            name='CON',
        ),
        migrations.DeleteModel(
            name='DEX',
        ),
        migrations.DeleteModel(
            name='HD',
        ),
        migrations.DeleteModel(
            name='HP',
        ),
        migrations.DeleteModel(
            name='INT',
        ),
        migrations.DeleteModel(
            name='STR',
        ),
    ]
