# Generated by Django 2.0 on 2017-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20171203_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='default name', max_length=30),
        ),
    ]
